/************************************************************************
*
*  Example Program:
*    MultiDeviceDynamicAcqAndGen-SourceSyncTClk.c
*
*  Description:
*    Synchronizes the internal sample clocks of two devices using NI-TClk,
*    then generates a simple pattern on the specified lines.
*
*    Using the Source Synchronous method, two other devices acquire the
*    pattern generated by the first two devices.
*
*  Pin Connection Information:
*    Connect the exported sample clock (default: DDC Clk-Out) from the
*    generation devices to the clock input terminal (default: Strobe)
*    on the acquisition devices, and connect the Data Active Event
*    (default PFI1) to the Acquisition Start Trigger (default PFI2).
*
*    If there are more acquisition devices than there are generation
*    devices, there may be termination and signal strength issues to
*    consider when routing any signal from a single source to multiple
*    destinations. See the section named Termination in the NI Digital
*    Waveform Generator/Analyzer Help for more information.
*
*
************************************************************************/


/* Includes */
#include <stdio.h>
#include "niHSDIO.h"
#include "niTClk.h"

/* Defines */
#define WAVEFORM_SIZE 1024
#define SAMPLES_TO_READ 1024
#define GEN_DEVICE_COUNT 2
#define ACQ_DEVICE_COUNT 2

/* These two functions were created simply to make the main program easier to read */
ViStatus setupGenerationDevice (ViRsrc genDeviceID, ViConstString genChannelList, ViConstString sampleClockOutputTerminal,
                                ViReal64 sampleClockRate, ViConstString dataActiveEventDestination, ViUInt32 waveformData[WAVEFORM_SIZE],
                                ViConstString waveformName, ViSession *genViPtr);

ViStatus setupAcquisitionDevice (ViRsrc acqDeviceID, ViConstString acqChannelList, ViConstString sampleClockSource,
                                 ViReal64 sampleClockRate, ViConstString startTriggerSource, ViSession *genViPtr);

int main(void)
{

   ViReal64 sampleClockRate = 50.0e6;
   ViStatus error = VI_SUCCESS;
   ViChar errDesc[1024];
   ViInt32 i;

   /* Generation */
   ViRsrc genDeviceID[GEN_DEVICE_COUNT] = {"PXI1Slot2","PXI1Slot3"};
   ViConstString genChannelList = "0-15";
   ViConstString sampleClockOutputTerminal = NIHSDIO_VAL_DDC_CLK_OUT_STR;
   ViConstString dataActiveEventDestination = NIHSDIO_VAL_PFI1_STR;
   ViUInt32 waveformData[WAVEFORM_SIZE];
   /* Note that the data type of waveformData may need to change
      if your device's default data width is not 4 bytes. */
   ViConstString waveformName = "myWfm";
   ViSession genVi[GEN_DEVICE_COUNT];

   /* Acquisition */
   ViRsrc acqDeviceID[ACQ_DEVICE_COUNT] = {"PXI1Slot4","PXI1Slot5"};
   ViConstString acqChannelList = "0-15";
   ViConstString sampleClockSource = NIHSDIO_VAL_STROBE_STR;
   ViConstString startTriggerSource = NIHSDIO_VAL_PFI2_STR;
   ViInt32 msReadTimeout = 10000;
   ViUInt32 patternRead[ACQ_DEVICE_COUNT][SAMPLES_TO_READ];
   /* Note that the data type of waveformData may need to change
      if your device's default data width is not 4 bytes. */
   ViInt32 numSamplesRead[ACQ_DEVICE_COUNT];
   ViSession acqVi[ACQ_DEVICE_COUNT];

   /* Initialize all ViSession variables to VI_NULL */
   for (i = 0; i < GEN_DEVICE_COUNT; i++)
      genVi[i] = VI_NULL;
   for (i = 0; i < ACQ_DEVICE_COUNT; i++)
      acqVi[i] = VI_NULL;

   /* Populate waveform with ramp data */
   for (i = 0; i < WAVEFORM_SIZE; i++)
      waveformData[i] = i;

   /* Initialize, configure, and write waveforms to generation device */
   for (i = 0; i < GEN_DEVICE_COUNT; i++)
      checkErr(setupGenerationDevice (genDeviceID[i], genChannelList, sampleClockOutputTerminal,
               sampleClockRate, dataActiveEventDestination, waveformData, waveformName, &genVi[i]));

   /* Configure Generation Devices for Homogeneous Triggers */
   checkErr(niTClk_ConfigureForHomogeneousTriggers (GEN_DEVICE_COUNT, genVi));

   /* Synchronize All Generation Devices */
   checkErr(niTClk_Synchronize (GEN_DEVICE_COUNT, genVi, 0.0));

   /* Commit settings on generation devices so the sample clocks will start.
   This must run before Initiate is run for the Acquisition sessions */
   for (i = 0; i < GEN_DEVICE_COUNT; i++)
      checkErr(niHSDIO_CommitDynamic (genVi[i]));

   /* Initialize, Configure, and Initiate Acquisition Sessions */
   for (i = 0; i < ACQ_DEVICE_COUNT; i++)
      checkErr(setupAcquisitionDevice  (acqDeviceID[i], acqChannelList, sampleClockSource,
               sampleClockRate, startTriggerSource, &acqVi[i]));


      /* Initiate synchronized generation. This function must be run after the
      acquisition sessions are initiated and waiting for a start trigger.
   Otherwise, the generation may begin before the acquisition is ready to receive data. */
   checkErr(niTClk_Initiate (GEN_DEVICE_COUNT, genVi));

   /* Fetch Waveform data from device */
   /* Note that you may need to use a different Fetch function
      if your device's default data width is not 4 bytes. */
   for (i = 0; i < ACQ_DEVICE_COUNT; i++)
      checkErr(niHSDIO_FetchWaveformU32 (acqVi[i], SAMPLES_TO_READ, msReadTimeout,
               &numSamplesRead[i], patternRead[i]));

Error:

   if (error == VI_SUCCESS)
   {
      /* print result */
      printf("Done without error.\n");
      for (i = 0; i < ACQ_DEVICE_COUNT; ++i)
      {
         printf("Number of samples read for device %s = %d.\n", acqDeviceID[i], numSamplesRead[i]);
      }
   }
   else
   {
      printf("Error encountered\n===================\n");

      /*  Get errors from NI-HSDIO sessions first.  Calling niHSDIO_GetError returns
          the error and clears the error for that session.  Calling
          niTClk_GetExtendedErrorInfo only returns an error generated by NI-TClk. */

      for (i = 0; i < GEN_DEVICE_COUNT; i++)
      {
         niHSDIO_GetError(genVi[i], &error, sizeof(errDesc)/sizeof(ViChar), errDesc);
         if (error != VI_SUCCESS)
            printf("Device ID: %s\nError Description: %s\n", genDeviceID[i], errDesc);

         /* Clear error description buffer to prevent the error from being printed
         multiple times */
         errDesc[0] = '\0';
      }

      for (i = 0; i < ACQ_DEVICE_COUNT; i++)
      {
         niHSDIO_GetError(acqVi[i], &error, sizeof(errDesc)/sizeof(ViChar), errDesc);
         if (error != VI_SUCCESS)
            printf("Device ID: %s\nError Description: %s\n", acqDeviceID[i], errDesc);

         /* Clear error description buffer to prevent the error from being printed
         multiple times */
         errDesc[0] = '\0';
      }

      niTClk_GetExtendedErrorInfo(errDesc, sizeof(errDesc)/sizeof(ViChar));
      printf("%s\n",errDesc);

   }

   /* close the sessions */
   for (i = 0; i < GEN_DEVICE_COUNT; i++)
      niHSDIO_close(genVi[i]);

   for (i = 0; i < ACQ_DEVICE_COUNT; i++)
      niHSDIO_close(acqVi[i]);

   /* prompt to exit (for pop-up console windows) */
   printf("\nHit <Enter> to continue...\n");
   getchar();

   return error;
}

ViStatus setupGenerationDevice(ViRsrc genDeviceID, ViConstString genChannelList, ViConstString sampleClockOutputTerminal,
                               ViReal64 sampleClockRate,ViConstString dataActiveEventDestination, ViUInt32 waveformData[WAVEFORM_SIZE],
                               ViConstString waveformName, ViSession *genViPtr)
{

   ViStatus error = VI_SUCCESS;
   ViSession genVi = VI_NULL;

   /* Initialize generation session */
   checkErr(niHSDIO_InitGenerationSession (
            genDeviceID, VI_FALSE, VI_FALSE, VI_NULL, &genVi));

   /* Assign channels for dynamic generation */
   checkErr(niHSDIO_AssignDynamicChannels (genVi, genChannelList));


   /* Configure Sample Clock */
   checkErr(niHSDIO_ConfigureSampleClock (
            genVi, NIHSDIO_VAL_ON_BOARD_CLOCK_STR, sampleClockRate));

   /* Export Sample Clock */
   checkErr(niHSDIO_ExportSignal (
            genVi, NIHSDIO_VAL_SAMPLE_CLOCK, VI_NULL, sampleClockOutputTerminal));

   /* Export data active event */
   checkErr(niHSDIO_ExportSignal(genVi, NIHSDIO_VAL_DATA_ACTIVE_EVENT,
            VI_NULL, dataActiveEventDestination));

   /* Write waveform to device */
   /* Note that you may need to use a different Write function
      if your device's default data width is not 4 bytes. */
   checkErr(niHSDIO_WriteNamedWaveformU32(genVi, waveformName, WAVEFORM_SIZE,
            waveformData));


Error:

   *genViPtr = genVi;

   return error;
}


ViStatus setupAcquisitionDevice (ViRsrc acqDeviceID, ViConstString acqChannelList, ViConstString sampleClockSource,
                                 ViReal64 sampleClockRate, ViConstString startTriggerSource, ViSession *acqViPtr)
{
   ViStatus error = VI_SUCCESS;
   ViSession acqVi = VI_NULL;

   /* Initialize acquisition session */
   checkErr(niHSDIO_InitAcquisitionSession(
      acqDeviceID, VI_FALSE, VI_FALSE, VI_NULL, &acqVi));

   /* Assign channels for dynamic acquisition */
   checkErr(niHSDIO_AssignDynamicChannels (acqVi, acqChannelList));


   /* Configure clocking parameters */
   checkErr(niHSDIO_ConfigureSampleClock(
            acqVi, sampleClockSource, sampleClockRate));

   /* Configure start trigger */
   checkErr(niHSDIO_ConfigureDigitalEdgeStartTrigger(acqVi,
            startTriggerSource, NIHSDIO_VAL_RISING_EDGE));

   /* Configure the number of samples to acquire to device */
   checkErr(niHSDIO_ConfigureAcquisitionSize(
            acqVi, SAMPLES_TO_READ, 1));

   /* Initiate Acquisition */
   checkErr(niHSDIO_Initiate (acqVi));

Error:

   *acqViPtr = acqVi;

   return error;

}
