//////////////////////////////////////////////////////////////////////////////
//
//  Title     : TriggeredGrabDlg.h
//  Project   : NI-IMAQdx
//  Created   : 8/25/2006 @ 07:30:26
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform a triggered, high-level grab acquisition,
//              built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_TRIGGEREDGRABDLG_H__611586ED_5DCE_434A_A9C8_34A736CD61AC__INCLUDED_)
#define AFX_TRIGGEREDGRABDLG_H__611586ED_5DCE_434A_A9C8_34A736CD61AC__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#include "NIIMAQdx.h"
#include "nivision.h"


//============================================================================
//  Class CTriggeredGrabDlg
//============================================================================
class CTriggeredGrabDlg : public CDialog
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CTriggeredGrabDlg(CWnd* pParent = NULL);	// standard constructor

    //------------------------------------------------------------------------
    //  Member data (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_DATA(CTriggeredGrabDlg)
	enum { IDD = IDD_TRIGGEREDGRAB_DIALOG };
	CComboBox	triggerActivationControl;
	CComboBox	triggerModeControl;
	CButton	initializeButton;
	CEdit	camNameControl;
	CButton	stopButton;
	CButton	grabButton;
	UINT	actualBufferNumber;
	CString	camName;
	CString	FrameRateString;
	//}}AFX_DATA

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CTriggeredGrabDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support
	//}}AFX_VIRTUAL

protected:
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
	HICON m_hIcon;

    //------------------------------------------------------------------------
    //  Message map methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_MSG(CTriggeredGrabDlg)
	virtual BOOL OnInitDialog();
	afx_msg void OnGrab();
	afx_msg void OnStop();
	afx_msg void OnQuit();
    afx_msg LRESULT OnUpdateDialog(WPARAM, LPARAM);
	afx_msg void OnChangeTrigger();
	afx_msg void OnInitialize();
	afx_msg void OnChangeCamname();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

private:
    //------------------------------------------------------------------------
    //  Methods
    //------------------------------------------------------------------------
    static UINT GrabThreadFunc(LPVOID param);
	UINT GrabThreadFuncInternal ();
    void StopGrabThread();
    void DisplayNIIMAQdxError(IMAQdxError error);
    void DisplayNIVisionError(int error);
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
    SESSION_ID session;
    Image* image;
    CWinThread* grabThread;
    bool stopThread;
	IMAQdxEnumItem* triggerMode;
	IMAQdxEnumItem* triggerActivation;
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TRIGGEREDGRABDLG_H__611586ED_5DCE_434A_A9C8_34A736CD61AC__INCLUDED_)
