//////////////////////////////////////////////////////////////////////////////
//
//  Title     : TriggeredGrab.h
//  Project   : NI-IMAQdx
//  Created   : 8/24/2006 @ 22:50:02
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform a triggered, high-level grab acquisition,
//              built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_TRIGGEREDGRAB_H__A71F0ED2_6957_472A_B4CD_BE26B22156FF__INCLUDED_)
#define AFX_TRIGGEREDGRAB_H__A71F0ED2_6957_472A_B4CD_BE26B22156FF__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols

//============================================================================
//  Class CTriggeredGrabApp
//============================================================================
class CTriggeredGrabApp : public CWinApp
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CTriggeredGrabApp();

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CTriggeredGrabApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CTriggeredGrabApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TRIGGEREDGRAB_H__A71F0ED2_6957_472A_B4CD_BE26B22156FF__INCLUDED_)
