//////////////////////////////////////////////////////////////////////////////
//
//  Title     : GrabDlg.h
//  Project   : NI-IMAQdx
//  Created   : 8/25/2006 @ 07:30:26
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform a simple, high-level grab acquisition,
//              built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_GRABDLG_H__18B386D1_F88E_4283_87B9_816064E2B0EB__INCLUDED_)
#define AFX_GRABDLG_H__18B386D1_F88E_4283_87B9_816064E2B0EB__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#include "NIIMAQdx.h"
#include "nivision.h"


//============================================================================
//  Class CGrabDlg
//============================================================================
class CGrabDlg : public CDialog
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CGrabDlg(CWnd* pParent = NULL);	// standard constructor

    //------------------------------------------------------------------------
    //  Member data (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_DATA(CGrabDlg)
	enum { IDD = IDD_GRAB_DIALOG };
	CButton	stopButton;
	CButton	grabButton;
	CEdit	camNameControl;
	CString	camName;
	CString	FrameRateString;
	UINT	actualBufferNumber;
	//}}AFX_DATA

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CGrabDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support
	//}}AFX_VIRTUAL

protected:
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
	HICON m_hIcon;

    //------------------------------------------------------------------------
    //  Message map methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_MSG(CGrabDlg)
	virtual BOOL OnInitDialog();
	afx_msg void OnQuit();
	afx_msg void OnGrab();
	afx_msg void OnStop();
    afx_msg LRESULT OnUpdateDialog(WPARAM, LPARAM);
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

private:
    //------------------------------------------------------------------------
    //  Methods
    //------------------------------------------------------------------------
    static UINT GrabThreadFunc(LPVOID param);
	UINT GrabThreadFuncInternal ();
    void StopGrabThread();
    void DisplayNIIMAQdxError(IMAQdxError error);
    void DisplayNIVisionError(int error);
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
    SESSION_ID session;
    Image* image;
    CWinThread* grabThread;
    bool stopThread;
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GRABDLG_H__18B386D1_F88E_4283_87B9_816064E2B0EB__INCLUDED_)
