/************************************************************************
*
*  Example Program:
*    MultiDeviceDynamicGenerationTClk.c
*
*  Description:
*    Synchronizes the internal sample clocks of two devices using NI-TClk,
*      then generates a simple pattern on specified channels.
*    This example implicitly uses the 10 MHz reference clock and the
*     start trigger.  If used in a PXI chassis, that chassis must be
*     properly configured in MAX.  If this example is used with PCI
*     devices, a RTSI cable must be properly configured in MAX.
*
*  Pin Connection Information:
*    None.
*
************************************************************************/


/* Includes */
#include <stdio.h>
#include "niHSDIO.h"
#include "niTClk.h"

/* Defines */
#define WAVEFORM_SIZE 1024
#define DEVICE_COUNT 2

int main(void)
{
   ViRsrc deviceID[DEVICE_COUNT] = {"PXI1Slot2","PXI1Slot3"};
   ViConstString channelList = "0-15";
   ViReal64 sampleClockRate = 50.0e6;
   ViUInt32 waveformData[WAVEFORM_SIZE];
   /* Note: You may need to change the data type of waveformData
      if the default data width of your device is not 4 bytes */
   ViConstString waveformName = "myWfm";
   ViInt32 msTimeout = 10000;

   ViSession vi[DEVICE_COUNT];
   ViStatus error = VI_SUCCESS;
   ViChar errDesc[1024];
   ViInt32 i;


   /* Populate waveform with ramp data */
   for (i = 0; i < WAVEFORM_SIZE; i++)
      waveformData[i] = i;

   for (i = 0; i < DEVICE_COUNT; i++)
   {
      /* Initialize generation session */
      checkErr(niHSDIO_InitGenerationSession(
               deviceID[i], VI_FALSE, VI_FALSE, VI_NULL, &vi[i]));

      /* Assign channels for dynamic generation */
      checkErr(niHSDIO_AssignDynamicChannels (vi[i], channelList));


      /* Configure sample clock parameters */
      checkErr(niHSDIO_ConfigureSampleClock(
               vi[i], NIHSDIO_VAL_ON_BOARD_CLOCK_STR, sampleClockRate));

      /* Write waveform to device */
      /* Note: You may need to use a different Write function if
         your device's default data width is not 4 bytes. */
      checkErr(niHSDIO_WriteNamedWaveformU32(
               vi[i], waveformName, WAVEFORM_SIZE, waveformData));
   }

   /*Configure all devices for Homogeneous Triggers */
   checkErr(niTClk_ConfigureForHomogeneousTriggers (DEVICE_COUNT, vi));

   /* Synchronize all devices */
   checkErr(niTClk_Synchronize (DEVICE_COUNT, vi, 0));

   /* Initiate generation on all devices simultaneously */
   checkErr(niTClk_Initiate (DEVICE_COUNT, vi));

   /* Wait for generation to complete. The timeout parameter uses units of seconds */
   checkErr(niTClk_WaitUntilDone (DEVICE_COUNT, vi, msTimeout/1000));

Error:

   if (error == VI_SUCCESS)
   {
      /* print result */
      printf("Done without error.\n");
   }
   else
   {
      printf("\nError encountered\n===================\n");

      /*  Get errors from NI-HSDIO sessions first.  Calling niHSDIO_GetError returns
      the error and clears the error for that session.  Calling
      niTClk_GetExtendedErrorInfo only returns an error generated by NI-TClk. */

      for (i = 0; i < DEVICE_COUNT; i++)
      {
         niHSDIO_GetError(vi[i], &error, sizeof(errDesc)/sizeof(ViChar), errDesc);
         if (error != VI_SUCCESS)
            printf("Device ID: %s\n%s\n",deviceID[i],errDesc);

         /* Clear error description buffer to prevent the error from being printed
         multiple times */
         errDesc[0] = '\0';
      }

      niTClk_GetExtendedErrorInfo(errDesc, sizeof(errDesc)/sizeof(ViChar));
      printf("%s\n",errDesc);

   }

   /* close the sessions */
   for (i = 0; i < DEVICE_COUNT; i++)
      niHSDIO_close(vi[i]);

   /* prompt to exit (for pop-up console windows) */
   printf("\nHit <Enter> to continue...\n");
   getchar();

   return error;
}
