//////////////////////////////////////////////////////////////////////////////
//
//  Title     : GrabBasicAttr.h
//  Project   : NI-IMAQdx
//  Created   : 2/12/2008 @ 10:19:26
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform a simple, high-level grab acquisition,
//              with basic attribute support built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_GRAB_H__94D985BE_BEAB_40C5_A2A7_0F9DA4D058D9__INCLUDED_)
#define AFX_GRAB_H__94D985BE_BEAB_40C5_A2A7_0F9DA4D058D9__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols

//============================================================================
//  Class CGrabBasicAttrApp
//============================================================================
class CGrabBasicAttrApp : public CWinApp
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CGrabBasicAttrApp();

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CGrabBasicAttrApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CGrabBasicAttrApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};


//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GRAB_H__94D985BE_BEAB_40C5_A2A7_0F9DA4D058D9__INCLUDED_)
