//////////////////////////////////////////////////////////////////////////////
//
//  Title     : LLGrabAsync.h
//  Project   : NI-IMAQdx
//  Created   : 8/29/2006 @ 18:02:02
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform an asynchronous, low-level grab 
//              acquisition, built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_LLGRABASYNC_H__3C27C347_4D44_4568_9F3E_A2F49E2F61AF__INCLUDED_)
#define AFX_LLGRABASYNC_H__3C27C347_4D44_4568_9F3E_A2F49E2F61AF__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols

//============================================================================
//  Class CLLGrabAsyncApp
//============================================================================
class CLLGrabAsyncApp : public CWinApp
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CLLGrabAsyncApp();

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CLLGrabAsyncApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CLLGrabAsyncApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LLGRABASYNC_H__3C27C347_4D44_4568_9F3E_A2F49E2F61AF__INCLUDED_)
