//////////////////////////////////////////////////////////////////////////////
//
//  Title     : LLGrabAsyncDlg.h
//  Project   : NI-IMAQdx
//  Created   : 8/29/2006 @ 18:05:26
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform an asynchronous, low-level grab 
//              acquisition, built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_LLGRABASYNCDLG_H__44B3A2E2_1ED8_40ED_9A67_D7DB9A5B4C1A__INCLUDED_)
#define AFX_LLGRABASYNCDLG_H__44B3A2E2_1ED8_40ED_9A67_D7DB9A5B4C1A__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#include "NIIMAQdx.h"
#include "nivision.h"


//============================================================================
//  Class CLLGrabAsyncDlg
//============================================================================
class CLLGrabAsyncDlg : public CDialog
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CLLGrabAsyncDlg(CWnd* pParent = NULL);	// standard constructor

    //------------------------------------------------------------------------
    //  Member data (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_DATA(CLLGrabAsyncDlg)
	enum { IDD = IDD_LLGRABASYNC_DIALOG };
	CEdit	camNameControl;
	CButton	stopButton;
	CButton	grabButton;
	UINT	actualBufferNumber;
	CString	camName;
	CString	FrameRateString;
	//}}AFX_DATA

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CLLGrabAsyncDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support
	//}}AFX_VIRTUAL

protected:
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
	HICON m_hIcon;

    //------------------------------------------------------------------------
    //  Message map methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_MSG(CLLGrabAsyncDlg)
	virtual BOOL OnInitDialog();
	afx_msg void OnGrab();
	afx_msg void OnStop();
	afx_msg void OnQuit();
    afx_msg LRESULT OnUpdateDialog(WPARAM, LPARAM);
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

private:
    //------------------------------------------------------------------------
    //  Methods
    //------------------------------------------------------------------------
    static uInt32 __stdcall FrameDoneCallback (IMAQdxSession session, uInt32 bufferNumber, void* callbackData);
    uInt32 FrameDoneCallbackInternal (IMAQdxSession session, uInt32 bufferNumber);
    void DisplayNIIMAQdxError(IMAQdxError error);
    void DisplayNIVisionError(int error);
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
    SESSION_ID session;
    Image* image;
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LLGRABASYNCDLG_H__44B3A2E2_1ED8_40ED_9A67_D7DB9A5B4C1A__INCLUDED_)
