/************************************************************************
*
*  Example Program:
*    MultiDeviceDynamicAcquisitionTClk.c
*
*  Description:
*    Synchronizes the internal sample clocks of two devices using NI-TClk,
*      then acquires a simple pattern on both devices.
*    This example implicitly uses the 10 MHz reference clock and the
*     start trigger.  If used in a PXI chassis, that chassis must be
*     properly configured in MAX.  If this example is used with PCI
*     devices, a RTSI cable must be properly configured in MAX.
*
*  Pin Connection Information:
*    None.
*
************************************************************************/


/* Includes */
#include <stdio.h>
#include "niHSDIO.h"
#include "niTClk.h"

/* Defines */
#define SAMPLES_TO_READ 1024
#define DEVICE_COUNT 2

int main(void)
{
   ViRsrc deviceID[DEVICE_COUNT] = {"PXI1Slot2","PXI1Slot3"};
   ViConstString channelList = "0-15";
   ViReal64 sampleClockRate = 50.0e6;
   ViInt32 msReadTimeout = 10000;
   ViUInt32 patternRead[DEVICE_COUNT][SAMPLES_TO_READ];
   /* Note: You may need to change the data type of patternRead
   depending on the default data width of your device. */

   ViSession vi[DEVICE_COUNT];
   ViInt32 numSamplesRead[DEVICE_COUNT];
   ViStatus error = VI_SUCCESS;
   ViChar errDesc[1024];

   int i;

   for (i = 0; i < DEVICE_COUNT; ++i)
   {
      vi[i] = VI_NULL;
   }

   for (i = 0; i < DEVICE_COUNT; ++i)
   {
      /* Initialize acquisition session */
      checkErr(niHSDIO_InitAcquisitionSession(
               deviceID[i], VI_FALSE, VI_FALSE, VI_NULL, &vi[i]));

      /* Assign channels for dynamic acquisition */
      checkErr(niHSDIO_AssignDynamicChannels (vi[i], channelList));


      /* Configure sample clock parameters */
      checkErr(niHSDIO_ConfigureSampleClock(
               vi[i], NIHSDIO_VAL_ON_BOARD_CLOCK_STR, sampleClockRate));

      /* Configure the number of samples to acquire to device */
      checkErr(niHSDIO_ConfigureAcquisitionSize(vi[i], SAMPLES_TO_READ, 1));

   }

   /* Configure Devices for Homogeneous Triggers */
   checkErr(niTClk_ConfigureForHomogeneousTriggers (DEVICE_COUNT,vi));

   /* Synchronize All Devices */
   checkErr(niTClk_Synchronize (DEVICE_COUNT, vi,0));

   /* Initiate Acquisition on all Devices */
   checkErr(niTClk_Initiate (DEVICE_COUNT, vi));

   /* Read data from device */
   /* Note: You may need to use a different Fetch function
   depending on the data width of your device. You may query the
   device's data width with the Data Width attribute. */
   for (i = 0; i < DEVICE_COUNT; i++)
      checkErr(niHSDIO_FetchWaveformU32 (
               vi[i], SAMPLES_TO_READ, msReadTimeout,
               &numSamplesRead[i], patternRead[i]));

   /* Wait until all devices are finished. The timeout parameter uses units of seconds */
   checkErr(niTClk_WaitUntilDone (DEVICE_COUNT, vi, msReadTimeout/1000));
Error:

   if (error == VI_SUCCESS)
   {
      printf("Done without error.\n");

      /* print result */
      for (i = 0; i < DEVICE_COUNT; ++i)
         printf("Number of samples read by %s = %d.\n", deviceID[i], numSamplesRead[i]);
   }
   else
   {
      printf("\nError encountered\n===================\n");

      /*  Get errors from NI-HSDIO sessions first.  Calling niHSDIO_GetError returns
      the error and clears the error for that session.  Calling
      niTClk_GetExtendedErrorInfo only returns an error generated by NI-TClk. */
      for (i = 0; i < DEVICE_COUNT; i++)
      {
         niHSDIO_GetError(vi[i], &error, sizeof(errDesc)/sizeof(ViChar), errDesc);
         if (error != VI_SUCCESS)
            printf("Device ID: %s\n%s\n",deviceID[i],errDesc);

         /* Clear error description buffer to prevent the error from being printed
         multiple times */
         errDesc[0] = '\0';
      }

      niTClk_GetExtendedErrorInfo(errDesc, sizeof(errDesc)/sizeof(ViChar));
      printf("%s\n",errDesc);
   }

   /* close the sessions */
   for (i = 0; i < DEVICE_COUNT; i++)
      niHSDIO_close(vi[i]);

   /* prompt to exit (for pop-up console windows) */
   printf("\nHit <Enter> to continue...\n");
   getchar();
   return error;
}
