//////////////////////////////////////////////////////////////////////////////
//
//  Title     : LLSnap.h
//  Project   : NI-IMAQdx
//  Created   : 8/29/2006 @ 13:04:02
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform a simple, low-level snap acquisition,
//              built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_LLSNAP_H__63C5A7E2_0EBC_4F84_AAD2_47637A369CF9__INCLUDED_)
#define AFX_LLSNAP_H__63C5A7E2_0EBC_4F84_AAD2_47637A369CF9__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols

//============================================================================
//  Class CLLSnapApp
//============================================================================
class CLLSnapApp : public CWinApp
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CLLSnapApp();

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CLLSnapApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CLLSnapApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LLSNAP_H__63C5A7E2_0EBC_4F84_AAD2_47637A369CF9__INCLUDED_)
