//////////////////////////////////////////////////////////////////////////////
//
//  Title     : LLGrabDlg.h
//  Project   : NI-IMAQdx
//  Created   : 8/29/2006 @ 10:25:26
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform a simple, low-level grab acquisition,
//              built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_LLGRABDLG_H__60965484_23A4_4B01_9509_DDEDAE83F1DE__INCLUDED_)
#define AFX_LLGRABDLG_H__60965484_23A4_4B01_9509_DDEDAE83F1DE__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#include "NIIMAQdx.h"
#include "nivision.h"


//============================================================================
//  Class CLLGrabDlg
//============================================================================
class CLLGrabDlg : public CDialog
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CLLGrabDlg(CWnd* pParent = NULL);	// standard constructor

    //------------------------------------------------------------------------
    //  Member data (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_DATA(CLLGrabDlg)
	enum { IDD = IDD_LLGRAB_DIALOG };
	CEdit	camNameControl;
	CButton	stopButton;
	CButton	grabButton;
	CString	camName;
	CString	FrameRateString;
	UINT	actualBufferNumber;
	//}}AFX_DATA

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CLLGrabDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);	// DDX/DDV support
	//}}AFX_VIRTUAL


protected:
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
	HICON m_hIcon;

    //------------------------------------------------------------------------
    //  Message map methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_MSG(CLLGrabDlg)
	virtual BOOL OnInitDialog();
	afx_msg void OnGrab();
	afx_msg void OnStop();
	afx_msg void OnQuit();
    afx_msg LRESULT OnUpdateDialog(WPARAM, LPARAM);
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

private:
    //------------------------------------------------------------------------
    //  Methods
    //------------------------------------------------------------------------
    static UINT GrabThreadFunc(LPVOID param);
	UINT GrabThreadFuncInternal();
    void StopGrabThread();
    void DisplayNIIMAQdxError(IMAQdxError error);
    void DisplayNIVisionError(int error);
    //------------------------------------------------------------------------
    //  Members
    //------------------------------------------------------------------------
    SESSION_ID session;
    Image* image;
    CWinThread* grabThread;
    bool stopThread;
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LLGRABDLG_H__60965484_23A4_4B01_9509_DDEDAE83F1DE__INCLUDED_)
