//////////////////////////////////////////////////////////////////////////////
//
//  Title     : LLGrab.h
//  Project   : NI-IMAQdx
//  Created   : 8/25/2006 @ 10:28:02
//  Platforms : All
//  Access    : Public
//  Purpose   : Illustrates how to perform a simple, low-level grab acquisition,
//              built using MSVC.
//
//////////////////////////////////////////////////////////////////////////////
#if !defined(AFX_LLGRAB_H__DBB34A73_962B_4DFB_B0AF_9BD95BD8CDA4__INCLUDED_)
#define AFX_LLGRAB_H__DBB34A73_962B_4DFB_B0AF_9BD95BD8CDA4__INCLUDED_

//============================================================================
//  Only include this file once
//============================================================================
#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//============================================================================
//  Includes
//============================================================================
#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols

//============================================================================
//  Class CLLGrabApp
//============================================================================
class CLLGrabApp : public CWinApp
{
public:
    //------------------------------------------------------------------------
    //  Constructor
    //------------------------------------------------------------------------
	CLLGrabApp();

    //------------------------------------------------------------------------
    //  Methods (generated by ClassWizard)
    //------------------------------------------------------------------------
	//{{AFX_VIRTUAL(CLLGrabApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CLLGrabApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LLGRAB_H__DBB34A73_962B_4DFB_B0AF_9BD95BD8CDA4__INCLUDED_)
